import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import moment from 'moment'
import { useEffect, useState } from 'react'
import axios from 'axios'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [isClient, setIsClient] = useState(false)
 
  useEffect(() => {
    setIsClient(true)
  }, [])

  const [time, setTime] = useState(moment().format('MMMM Do, YYYY - HH:mm:ss'))
  const [cars, setCars] = useState([])

  useEffect(()=>{
    setInterval(()=>{
      setTime(moment().format('MMMM Do, YYYY - HH:mm:ss'))
    },1000)

    axios
      .get('https://spe-academy.spesolution.com/api/recruitment', {
        headers: {
          Authorization: 'Bearer o7Ytbt9XQLI3PgtebJfKSXKEf0XHU74Y',
          "Content-Type": 'application/json'
        }
      })
      .then(res=>{
        console.log(res)
        setCars(res.data)
      })
      .catch(err=>{
        console.log(err)
      })
  },[])

  if(isClient) return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${inter.className}`}>
        <section className={styles.gradient}>
          <div className={styles.section1}>
            <div className={styles.content}>
              <div className={styles.date}>{time}</div>
              <div className={styles.info}>&lt; SPE / Frontend &gt;</div>
            </div>
          </div>
        </section>

        <section style={{background:'#eee', padding:80}}>
          <h2 style={{textAlign:'center', marginTop:80}}>SPE Frontend Shop</h2>
          <table cellPadding={16} cellSpacing={0}>
            <thead>
              <tr>
                <td>PRODUCT</td>
                <td>QUANTITY</td>
                <td>SUBTOTAL</td>
              </tr>
            </thead>
            <tbody>
              {cars.map((car, index)=>(
                <tr key={index}>
                  <td>
                    <div style={{display:'flex', gap:16}}>
                      <Image src={car.product.media_url} height={80} width={100} alt={car.product.name} />
                      <div>
                        <div style={{color: 'blue'}}>{car.product.code}</div>
                        <div>{car.product.name}</div>
                        <div>IDR. {parseFloat(car.product.price).toLocaleString()}</div>
                        <div style={{color:'salmon'}}>{car.product.stock} in stock</div>
                      </div>
                    </div>
                  </td>
                  <td className='center'>{car.quantity}</td>
                  <td className='center'>IDR. {parseFloat(car.quantity * car.product.price).toLocaleString()}</td>
                </tr>
              ))}

              <tr className='table-foot'>
                <td colSpan={2} style={{textAlign:'right'}}>TOTAL</td>
                <td className='center'>IDR. {cars.length && parseFloat(cars.reduce((prev,next)=> {return prev + (next.quantity * next.product.price)}, 0)).toLocaleString()}</td>
              </tr>
            </tbody>
          </table>
        </section>
      </main>
    </>
  )

  return 'Loading...'
}
